# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Drupal Diversity & Inclusion
email:
description: > # this means to ignore newlines until "baseurl:"
  Drupal Diversity & Inclusion is a collection of community-managed
  diversity initiatives within the Drupal community. We are all volunteers and are
  not affiliated with the Drupal Association.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: drupaldiversity
twitter_username: drupaldiversity
twitter_url: https://twitter.com/drupaldiversity
github_username:  drupaldiversity
logo: /assets/drupaldiversity_logo_300.png
author: drupaldiversity

social:
  name: Drupal Diversity
  links:
    - https://github.com/drupaldiversity
    - https://twitter.com/drupaldiversity

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-twitter-plugin
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
